name: Enossion Auto Archive

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */3 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update memory archive
        run: |
          mkdir -p logs
          echo "$(date) — heartbeat from enossion" >> logs/heartbeat.txt
          git init --initial-branch=main
          git config user.name "enossionbot"
          git config user.email "enossion@users.noreply.github.com"
          git add .
          git commit -m "Auto archive from enossion at $(date)" || echo "No changes"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
